name: update data

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - run: wget -q -O beanally.csv ${{ secrets.doc_url }}
      - run: if [[ $(wc -l <beanally.csv) -le 20 ]]; then exit 1; fi
      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add website changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.gh_token }}
          branch: main
      - name: crontab
        run: curl ${{ hc_url }}
