name: update data

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: wget -O beanally.csv ${{ secrets.doc_url }}
      - run: if [[ $(wc -l <beanally.csv) -le 20 ]]; then exit 1; fi
